name: 'terraform-azure-deployment'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

run-name: "${{ github.ref_name }}.${{ github.sha }}.${{ github.workflow }}."

env:
  TF_VERSION: '1.14.4'
  SUB_ID: ${{ secrets[format('AZURE_{0}_SUBSCRIPTION_ID', inputs.environment)] }}
  ARM_CLIENT_ID: ${{ secrets[format('AZURE_{0}_CLIENT_ID', inputs.environment)] }}
  ARM_CLIENT_SECRET: ${{ secrets[format('AZURE_{0}_CLIENT_SECRET', inputs.environment)] }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_CLI: false
  TF_FOLDER: 'infra'
  TF_LOG: info

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set subscription ID
        run: |
          cd ${{ env.TF_FOLDER }}
          SUBSCRIPTION_ID=${{ env.SUB_ID }}
          echo "ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID" >> $GITHUB_ENV

      - name: Terraform Init
        id: init
        run: |
          cd ${{ env.TF_FOLDER }}
          terraform init

      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ env.TF_FOLDER }}
          terraform plan -var-file=../${{ inputs.environment }}/terraform.tfvars -out=tfplan
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        run: |
          cd ${{ env.TF_FOLDER }}
          terraform apply -auto-approve tfplan